### PR TITLE
fix: handle brand name lookup KeyError

### PR DESCRIPTION
**Pull request by jsstevenson**
The December 2023 release includes a linkage between a concept and a brand name where the brand name is marked as deprecated (so we don't import it in the first place).

### CODE REVIEW

**Review by korikuzma — DISMISSED** [review]
@jsstevenson Thank you for the fast fix. Should we add this ID to the `TEST_IDS` [here](https://github.com/cancervariants/therapy-normalization/blob/52fdb61375deead4492c2e53ba22cfc67922e87e/tests/scripts/build_hemonc_data.py#L8)?

**Comment by jsstevenson** [comment]
no :(

**Comment by jsstevenson** [comment]
:////

**Review by korikuzma — APPROVED** [review]
💯

**Pull request merged**
