### PR TITLE
Issue 190

### LINKED ISSUE #190: Only ask for confirmation of using prod database once
When using the CLI to update the prod database, we get asked for confirmation twice to use the prod db - once at the beginning for therapy db and another time when updating hemonc for disease db. We should only have to confirm this once.

### PR DESCRIPTION
**Pull request by jsstevenson**
Close #190 

* If `THERAPY_NORM_PROD` is set, don't ask for additional confirmation to use production disease database unless the disease data appears to be incomplete

I am afraid to test this but I think it should work [famous last words]

### CODE REVIEW

**Review by korikuzma — COMMENTED** [review]
I don't think this is needed since in line 116, we have the condition `"THERAPY_NORM_PROD" not in environ`

**Comment by korikuzma** [comment]
Oh I think you're description meant to say if THERAPY_NORM_PROD is _not_ set

**Comment by korikuzma** [comment]
Ok wait I am getting confused with this PR

**Comment by korikuzma** [comment]
Looking back at this again. I made [this](https://github.com/cancervariants/therapy-normalization/commit/8e8e23a46174e15a9a06a3f57ab376cb2e36725e#diff-a288cd7ad11cc749e0e12d47766fe201bf0891fd2a97dec62fd59475672cdae8) commit the same day I made the issue, but I must've never closed the issue. I think we can close this PR and the issue. My bad!

**Comment by jsstevenson** [comment]
> Looking back at this again. I made this commit the same day I made the issue, but I must've never closed the issue. I think we can close this PR and the issue. My bad!

This explains so much!

**Pull request closed without merging**
